name: mlg-test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9472359563224018
title: MLG Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#6a6a6a'
    - '#c3c3c3'
    - '#383838'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
