name: mlg-test
favicon: null
layout_spectrum: 0.09290521591901779
typography_spectrum: 0.9472359563224018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8242008273955435
  lightness: 0.6268598698079586
  saturation: 0.022839774377644062
  rhythmicContrast: 0.31941759842447937
purpose: []
